### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by JellyBrick** [KiwiTalk/KiwiTalk#1]
## Working Prototype 만들기

기본적인 기능을 테스트할 수 있도록

## UI 프로토타이핑

- [x] 로그인
- 프로필
  - [x] #1962
  - [ ] #1963
  - [ ] PLUS친구 프로필
- [x] #1960
- 채팅방
  - [ ] 톡게시판
  - [x] #1964
    - [x] 공식 API로 만든 커스텀 Form 메시지
  - [ ] 보이스톡
  - [ ] 페이스톡
- [ ] 이모티콘 키보드
- [ ] #1966
  - [ ] #1965
    - [ ] 테마
    - [ ] #1970
  - [ ] #1969
    - [ ] #1967
  - [ ] 저장소
    - [ ] 오래된 파일/채팅 내역 삭제
    - [ ] 파일 저장 한도 설정
    - [ ] #1968
- [x] #1961
## 기능 구현
- [x] 계정 인증
  - [ ] ~~이미 다른 기기에서 로그인 되어있는 경우, IPad 모드로 로그인 시도 ("아이패드 모드로 로그인하시겠습니까?")~~
  - [ ] ~~IPad 모드가 실패한 경우~~ PC나 IPad 기기 강제 로그아웃 할 수 있게 UI 띄우기
- [x] 로그인
- [x] 채팅 알림
- [ ] 친구 목록 불러오기
- [ ] 방 목록 불러오기
- [ ] 알림톡 지원
- [ ] 채팅방 접속
  - [ ] 메시지 불러오기
  - [ ] 메시지 읽음 처리
  - [ ] 메시지 읽은 사람 리스트 불러오기
  - [ ] 메시지 읽씹 처리
  - [ ] 메시지 삭제 처리 + 복구
  - [ ] 투표 / 공지 / 선물 타입 메시지 수신 지원
  - [ ] 기타 PC버전 미지원 메시지 수신시 모양만 띄우고 ‘모바일에서 확인하세요’ 띄우기
- [ ] 메시지 검색하기
- [ ] 메시지 보내기
  - [ ] 사진/파일 첨부
  - [ ] 이모티콘 보내기
  - [ ] 해시태그 검색 기능
  - [ ] 캘린더 연동
  - [ ] 지도
  - [ ] 음성메시지
  - [ ] 연락처 전송
- [ ] 톡게시판 불러오기
  - [ ] 공지 불러오기
  - [ ] 투표 불러오기
- [ ] 보이스톡 (Opus) 
- [ ] 페이스톡 (x264asm (H.264))
- [ ] 프로필 불러오기
  - [ ] 프로필 수정 기록들 불러오기
  - [ ] 멜론 프로필뮤직 리스트 불러오기
  - [ ] 프로필 치장 아이템 배치 불러오기
- [ ] 내 프로필 수정하기
  - [ ] 프로필 치장 아이템 자유 배치 지원
  - [ ] 멜론 프로필뮤직 리스트 선택 지원
- [ ] 친구 추가하기
  - [ ] 주소록 연동하기
- [ ] 친구 삭제하기
- [ ] 친구 차단하기
  - [ ] 설정한 시간대에만 친구 차단하기 ex: 17:00~익일09:00
- [ ] 방 만들기
- [ ] 방 접근 제한하기
  - [ ] 설정한 시간대에만 메시지 입력 & 읽음 확인 제한하기
- [ ] 채팅방 숨기기
- [ ] 플러그인 지원
  - [ ] 커스텀 CSS 지원
- [ ] 프로그래밍 언어 구문 강조 
  - [ ] 자동 언어 감지 기능 (highlight.js)
  - [ ] 사용자가 수동 조정 가능
- [ ] 대화에 주의가 필요한 방 설정 (경고 메시지)
- [ ] 생체인식 로그인 구현 (일렉트론 - 크롬의 생체인식 API 사용)
- [ ] 예약 메시지
- [ ] 맥북 터치바 대응
- [ ] 데이터 저장
  - [ ] 채팅 내역
  - [ ] 역사
    - [ ] 프로필 사진
    - [ ] 상대
