### ISSUE TITLE
Design TODO

### ISSUE THREAD

**Issue by JellyBrick** [KiwiTalk/KiwiTalk#2]
- UI 컴포넌트 React로 제작(Storybook)

- UI 컴포넌트 제작 
  - [x] 포인트(하이라이트) 컬러 2개정도 잡고 그에 따른 컬러스킴 생성
  - [ ] 대화상자 디자인
  - [x] 버튼 state
- [x] 친구 목록 Mockup 제작
- [x] 채팅 목록 Mockup 제작
  - [ ] 오픈챗과 일반 그룹챗, 갠챗 구분해야함
- [ ] 프로필
  - [ ] 프로필 뷰어 - 카드형?
    - [ ] 일반 프로필
    - [ ] PLUS친구 프로필
- [x] 채팅방 Mockup 제작
  - [ ] 톡게시판 UI
  - [ ] 보이스톡 UI
  - [ ] 페이스톡 UI
  - [ ] 이모티콘 키보드
- [ ] 설정 UI 기획 / Mockup
  - [ ] 프로그램 UI 관련
    - [ ] 테마
    - [ ] 글꼴 및 글씨 크기
  - [ ] 보안
    - [ ] 신뢰할 수 없는 도메인 경고
  - [ ] 저장소
